### ISSUE TITLE
v6: Using `upsert` requires a db constraint

### ISSUE THREAD

**Issue by eugene1g** [voxpelli/node-connect-pg-simple#144]
The use of `upsert` means the `session` table must have a constraint marking the `sid` field as unique. This is currently not defined in https://github.com/voxpelli/node-connect-pg-simple/blob/master/table.sql so the existing table can be upgraded with this command:

```sql
alter table session add constraint sid_unique unique(sid);
```

Not sure if this is a documentation issue for V6, or the sql template should be updated

**Comment by voxpelli** [comment]
You have a valid point, though the `sid` is already as a primary key?

https://github.com/voxpelli/node-connect-pg-simple/blob/362b775eb3e333648ca30eddde73bb3ec43c3342/table.sql#L7

And has been so since the very beginning: https://github.com/voxpelli/node-connect-pg-simple/commit/fb490872bca2ffa81f50fd375bfd6404802f0a92

And the tests are passing as they should:

https://github.com/voxpelli/node-connect-pg-simple/blob/362b775eb3e333648ca30eddde73bb3ec43c3342/test/integration/express.spec.js#L85-L98

So it should be working fine?

**Comment by eugene1g** [comment]
You're right - `sid` is already a primary key and that implies uniq. In my codebase I used a slightly different structure for the session table, but didn't copy the last `alter` from your sql file, so this was a user error. Thanks!
