### ISSUE TITLE
Random deletion of expired sessions

### ISSUE THREAD

**Issue by bathos** [voxpelli/node-connect-pg-simple#15]
The following seems sort of arbitrary -- 5% of requests will trigger the deletion of expired sessions. Where's this number from? Why bind this cleanup event to request events at all?

    if (Math.random() < 0.05) {
      this.query('DELETE FROM ' + this.quotedTable() + ' WHERE expire < NOW()');
    }

**Comment by focusaurus** [comment]
One fork has some work on doing stale session cleanup on a timer completely decoupled from incoming requests. https://github.com/paquettea/node-connect-pg-simple/commit/311f5cea63f7e3cd3319f4b3372f0fdf65e7bdfa

**Comment by voxpelli** [comment]
It is very much arbitrary and I can't really remember why it was chosen as the initial solution – perhaps because it was a very simple quick way of achieving at least some kind of cleanup.

There's a PR in #13 to replace this with a less arbitrary mechanism and I will likely merge that and release that and a solution to #14 as a new version as soon as I get some time – hopefully this weekend or the next.

**Comment by bathos** [comment]
Oh, cool! (And now I know I ought to check pull reqs as well as issues before opening a new one).

**Comment by voxpelli** [comment]
Fixed by #13 and follow up #18 and released as `3.0.0`
