### ISSUE TITLE
RFC: Increase default prune interval to something like 15 minutes

### ISSUE THREAD

**Issue by voxpelli** [voxpelli/node-connect-pg-simple#162]
Does anyone have any feedback on whether this would be a good or a bad change for them?

To me it feels like there's no harm in doing this at a longer interval, as the code checking for a session already checks the timestamp and only returns valid active sessions. This pruning is more of a garbage collector and that we don't need to run 60 times an hour. 4 times an hour would be more appropriate I think.

If someone has a site with _lots_ of sessions, then of course they can change the default.

Will start by increasing from `1` to `5` minutes now, to not break anything for anyone.

**Comment by Sprax2013** [comment]
I personally have put `pruneSessionInterval` up to 24h because I don't see any reason not to. Sessions don't take a lot of space and I prefer one more time consuming query that one that could be very light but blocks an connection in the pool every minute (or five).
So I would think a higher value would be great on the next *major* or *minor* release
