### ISSUE TITLE
sessions not found when node.js server and DB server not having same time

### ISSUE THREAD

**Issue by sverkoye** [voxpelli/node-connect-pg-simple#25]
Came across a nice issue that happens when node.js and pgsql are not running on the same machine and where both machines were in different timezones (or simply had differences in their curren time). I'm posting a fix here in case anybody encounters this or wants to fix this inside the module.

The session prune and query functions use NOW() of pgsql while the insert/update statements are formed using node.js Date.now(), thus taking the time of the node.js server.

I fixed this for me by making sure all queries take the time from the same server. In this case I used the time from the node.js server in all cases. For anyone interested:

pruneSessions() then becomes:

```
this.query('DELETE FROM ' + this.quotedTable() + ' WHERE expire < to_timestamp($1)', [Date.now() / 1000], ....
```

and get() becomes:

```
this.query('SELECT sess FROM ' + this.quotedTable() + ' WHERE sid = $1 AND expire >= to_timestamp($2)', [sid, Date.now() / 1000], ...
```

I later found out the date on my DB server was 1 day off ;-)

**Comment by voxpelli** [comment]
Thanks for reporting this! They should ideally use the same time – and I would chose the database time to be that one time as one can have multiple node.js-servers talking to the same database and those node.js-servers might also have different times set on them.

If you have a PR I'll happily accept it, else I fix it when I get around to update the module next time :tada:

**Comment by elmigranto** [comment]
> If you have a PR I'll happily accept it

This sounds like a kind of problem `set timezone` on node's side should solve. On the other hand, SQL schema uses `timestamp` instead of `timestamptz`, so I'm not sure what would be an optimal course of action.

**Comment by voxpelli** [comment]
@elmigranto There can still be time issues though so ideally all timestamps used should have the same source

**Comment by voxpelli** [comment]
Oh, wow, was it almost a year ago I said I was going to fix this in the next release? I'm very sorry that I haven't yet done so yet!

**Comment by elmigranto** [comment]
> There can still be time issues though

Could you elaborate? If node and postgres are in different timezones (but with correct time), `timestamptz` should work just fine, given you provide correct timezone for connection (perhaps an constructor option?). If some have invalid time on clock, well, not much you can do here, I think.

**Comment by voxpelli** [comment]
@elmigranto In this particular modules the time issues most likely won't be very apparent as it at most will shorten or lengthen the lifetime of a session by a few seconds if the clock on the node.js machine and the database machine isn't in sync. As a session will very likely have a much much longer lifespan that a few seconds the impact will be negligible.

I would consider it best practice to always use the same source for the time though because it will matter when lifespans are very short or when there's eg. some cut off time like a publish date. If one always uses the same time source then no matter how wrong the clock is all times relative to it will always have the intended offsets.
