### ISSUE TITLE
multiple rows every 30 seconds in my store

### ISSUE THREAD

**Issue by jfbaquerocelis** [voxpelli/node-connect-pg-simple#27]
Hi, I want to ask and know why that every **30 seconds** a new row is created in my store?

I have the following configuration:
```javascript
app.use (session ({
    store : pgSession ({
        pg : require ('massive/node_modules/pg'),
        conString: "my ConString",
        tableName : 'session'
    }),
    secret: 'every secret',
    cookie: {maxAge: 1 * 24 * 60 * 60 * 1000},
    resave: false,
    saveUninitialized: true
}))
```

I am using `express-session` to session management. I hope you can help me with this because if you leave me a full day generate more than 2,000 records.

Thanks!!! :relaxed: :+1:

**Comment by voxpelli** [comment]
Sounds like you have a new visitor every 30 second and that you save all cookies for an entire day.

You may try to set the `saveUninitialized` to `false` as that should make it so that only sessions that have actually had some data added to it will be saved: https://github.com/expressjs/session#saveuninitialized That way you can hopefully avoid saving sessions for search bots that crawl you or for basic pings from services like Pingdom or whatever it could be that makes a request to you every 30 seconds.

A service like Pingdom, or any other bot or basic pinger/crawler, would by default not specify a cookie when making a request to you and thus each and every one of those requests would create a needless new session. The `saveUninitialized` settings seems to exist to tackle this very problem.

**Comment by jfbaquerocelis** [comment]
@voxpelli you are right! Now I think I know what the problem is. In my *development environment* is no error, but in a *production environment* error is generated. I have the application with ngix .... ngix have to do with that error, generate logs every 30 seconds?

**Comment by voxpelli** [comment]
@jfbaquerocelis Sorry for late response. Have you tried to set the `saveUninitialized` to `false` as suggested in my previous comment? There appears to be something that triggers new sessions to be created frequently and as long as those hasn't had any data added to them, setting that setting to `false` should stop them from reaching the database.

Nginx probably doesn't have anything to do with this directly – it's probably more a case of your application being available to the world wide web and one or more things there are making requests to your application that causes these sessions to be created.

**Comment by jfbaquerocelis** [comment]
@voxpelli Thanks for your contribution. I solved the problem. the problem was a scan program of intranet that maked the request every 30 seconds. what we did was cancel the requests that this system provide. :+1: :smiley:

**Comment by voxpelli** [comment]
Great!
