### ISSUE TITLE
Cannot use connection pool of application

### ISSUE THREAD

**Issue by lynxionxs** [voxpelli/node-connect-pg-simple#30]
Hi, this module wont use the connection pool module of the rest of my application. Why is that ?

```javascript
// db.js

var Promise = require('bluebird'),
    pgp = require('pg-promise')({
        promiseLib: Promise
    }),
    conf = require('./conf.js');

var db = pgp(conf.pgdb.conn);

module.exports = db;

// app.js 

var db = require('./db.js');
//...etc

var sessionOptions = {
    store : new PostgreSqlStore({
        pg : db // <--- db DOES NOT WORK
    })
};
```

**Comment by voxpelli** [comment]
Seems like you're sending in an instance of `pg-promise` rather than of `pg`.

Try changing it to:

```javascript
var sessionOptions = {
  store : new PostgreSqlStore({
    {
      pg : pgp.pg,
      conString : conf.pgdb.conn
    }
  })
};
```

The `pgp.pg` should expose the `pg`-module used by `pg-promise`: https://github.com/vitaly-t/pg-promise/blob/master/lib/index.js#L195

And the connection string needs to be added as that's how the pooling works when working against `pg` directly: https://github.com/voxpelli/node-connect-pg-simple/blob/master/index.js#L137

Hope that helps!

**Comment by lynxionxs** [comment]
@voxpelli your solution works, thanks

**Comment by vitaly-t** [comment]
That looks right :)
