### ISSUE TITLE
pg-promise

### ISSUE THREAD

**Issue by vitaly-t** [voxpelli/node-connect-pg-simple#32]
Would you consider a PR or a different branch to switch over to `pg-promise`?

It would simplify your code a lot, while also making it more reliable ;)

**Comment by MagnumDopus** [comment]
+2, this would hugely help me as well!

**Comment by voxpelli** [comment]
@MagnumDopus How could this internal change be hugely helpful to you?

On the main issue: I'm skeptic of introducing another dependency, not sure it would help more than it complicates things.

**Comment by MagnumDopus** [comment]
Sorry, and perhaps I am missing something due to me being so dumb, but my entire app relies on pg-promise, I do not instantiate any instances of standard pg anywhere, so being able to import and use my pg-promise db connection for the session store would just tidy things up.  I suppose I shouldn't say "hugely helpful" but I know for lots of people like me who use pg-promise entirely it'd be nice thats for sure.

**Comment by voxpelli** [comment]
@MagnumDopus So what you really want is a way to easily set this module up using an existing `pg-promise` setup – that makes sense, a different issue than this internal change though – could probably be achieved independently of it. Could you open a new issue for that so we can track it separately?

**Comment by vitaly-t** [comment]
b.t.w. the original question wasn't answered for 8 month :wink:

**Comment by voxpelli** [comment]
@vitaly-t yeah, sorry about that, wanted to look into it more – felt somewhat unproductive to just respond with: "I'm unsure and somewhat skeptical" ;) Coming around to do a sweep of updates on this project is on my opensource-todo

**Comment by vitaly-t** [comment]
@voxpelli well, if you decide to do so eventually, it will be very simple :wink:

**Comment by MagnumDopus** [comment]
I am terribly new and unfamiliar with github, but I should just open a whole new issue right?  There is no way to like... "branch" this chain?  (I am an idiot, yes).

**Comment by voxpelli** [comment]
@MagnumDopus You can always mention the number of this issue in the new one, using # followed by the number of this one, and the mention will appear here and they will be kind of connected, but that's as far as GitHub supports branching/linking between issues

**Comment by eugene1g** [comment]
As a temporary measure, I managed to use `pg-promise` by providing a mock for the `pg` object which just wraps native `pg-promise` magic -

```js
const _mockQueryFn = (queryString, params, queryCallback) => {
  pgPromiseInstance //<--- your reference to the pg-promise instance for the database
    .query(queryString, params)
    .then(result => queryCallback(null, { rows: result }))
    .catch(error => queryCallback(error));
};
const _mockPgObject = {
  connect: (conString, connectCallback) => {
    connectCallback(null, { query: _mockQueryFn }, () => {});
  }
};


// Now use this mock while configuring `session`
app.use(
    session({
      store: new pgSession({
        pg: _mockPgObject
      }),
      secret: "....",
      resave: false,
      saveUninitialized: false,
      cookie: { maxAge: 30 * 24 * 60 * 60 * 1000 }
    })
  );

```

**Comment by eugene1g** [comment]
FYI `pg-promise` is fixed to `pg@5.1` (see https://github.com/vitaly-t/pg-promise/issues/206), and `node-connect-pg-simple@4` is fixed to `pg@6` (because it uses pooling as per https://github.com/voxpelli/node-connect-pg-simple/issues/41). This means that `node-connect-pg-simple` >=4 cannot be used seamlessly with `pg-promise` right now.

**Comment by vitaly-t** [comment]
@eugene1g Used seamlessly = No, converted = Yes, it can be, because pg-promise hides the connections anyhow. So the change would mean simply throwing away any use of the pool. And when/if pg-promise gets upgraded to a newer pg, no change will be required here.

**Comment by eugene1g** [comment]
If @vitaly-t says it is so, who am I to argue? 

My snippet above (for V3) faked the `pg` parameter. Starting v4, we have to fake the "pool" parameter instead, so this example works instead -

```
const _mockQueryFn = (queryString, params, queryCallback) => {
  pgPromiseInstance //<--- your reference to the pg-promise instance for the database
    .query(queryString, params)
    .then(result => queryCallback(null, { rows: result }))
    .catch(error => queryCallback(error));
};

const _mockPgObject = {
  connect: (conString, connectCallback) => {
    connectCallback(null, { query: _mockQueryFn }, () => {});
  }
};

// Now use this mock while configuring `session`
app.use(
    session({
      store: new pgSession({
        // pg: _mockPgObject // node-connect-pg-simple@3
       pool: { query: _mockQueryFn} // node-connect-pg-simple@4
      }),
      secret: "....",
      resave: false,
      saveUninitialized: false,
      cookie: { maxAge: 30 * 24 * 60 * 60 * 1000 }
    })
  );
```

**Comment by vitaly-t** [comment]
It is a bit awkward, yes, but it least it works :)

**Comment by vitaly-t** [comment]
@eugene1g Alternatively, you can force pg-promise into the latest pg 6.x as shown there: https://github.com/vitaly-t/pg-promise/issues/206. It will work as reliably as pg 6.x does, which isn't great, unfortunately, that's why I've been holding back on the upgrade, no other reason, believe me.

**Comment by eugene1g** [comment]
If I must choose between monkey-patching the session config in one place vs using an unstable link to the database in all places, I'm gonna go with the awkward freedom of JavaScript and patch the hell out of it :D

**Comment by voxpelli** [comment]
Interesting, hmm, if someone were to provide a minimal PR that adds `pg-promise` support in addition to what is currently supported in this module then I could be open to merging it. Looks like it could be a very small change by the size of @eugene1g's hack 🙂 Perhaps a `pgPromise` property that one chose instead of the `pool`?

**Comment by vitaly-t** [comment]
@voxpelli why not to replace the whole thing? It isn't that much of code anyway. 

And your tests should show if there is any issue, if they are good ;)

**Comment by voxpelli** [comment]
@vitaly-t baby steps ;) for now I want to support `pg` itself, but looks like `pg-promise` is both a requested and sensible addition that can easily be supported simultaneously and without any additional breaking changes

**Comment by eugene1g** [comment]
@voxpelli  I'll do a PR

**Comment by voxpelli** [comment]
While I know this issue is about a total conversion from `pg` to `pg-promise` I think the support for `pg-promise` side by side with the support for `pg` is good enough, so I'll close this for now.

Only thing one could possibly imagining doing eventually is switching the built in module from `pg` to `pg-promise`, but `pg` should always be a supported option I think, to keep the module lean and simple.
