### ISSUE TITLE
 Cannot set property 'domain' of undefined

### ISSUE THREAD

**Issue by aybmab** [voxpelli/node-connect-pg-simple#42]
I'm getting the following error when trying to set this up:

events.js:24
  this.domain = null;
              ^

TypeError: Cannot set property 'domain' of undefined
    at EventEmitter.init (events.js:24:15)
    at EventEmitter (events.js:6:21)
    at Store (/project/node_modules/express-session/session/store.js:33:16)
    at PGStore (/project/node_modules/connect-pg-simple/index.js:19:11)

Any insight?

**Comment by aybmab** [comment]
Here's how I'm trying to set it up:

`
import pgSessionStore from 'connect-pg-simple'
import pg from './includes/pg/pgPromise.js' // my global instance of pgpromise
app.use(session(
  {
    store: new pgSessionStore(session)({
      pg : pg.pg,
      conString : 'postgresql://testuser:password@localhost:5432/testdb',
      tableName : 'st_user_sessions',
    }),
  	secret: 'some secret',
  	cookie: { maxAge: 365 * 24 * 60 * 60 * 1000 },
  	resave: false,
  	saveUninitialized: false
  }
))
`

**Comment by voxpelli** [comment]
You are missing a pair of parenthesis.

You should do: `new (pgSessionStore(session))({ ... })`

What you are currently doing: `new pgSessionStore(session)({ ... })`

That means that currently `new` is creating an instance of `pgSessionStore` rather than of the result of `pgSessionStore(session)` which is what it is meant to be doing.

First one injects the session object that contains the session `Store` to extend and retrieves a class that one can create an instance of, then one creates an instance of that returned class. It's a bit odd, and clearer if broken up into two statements rather than having that pair of additional parenthesis, but it's shorter with them.

Does it work with this proposed fix?

**Comment by aybmab** [comment]
This did it! Thanks!
